version: '3.4'

services:

  cataloguedb:
    image: :mongo
    
    

  catalogueapi:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue.API/CatalogueAPI/Dockerfile

volumes:
  mongo_data:
  
