version: '3.4'

services:

  cataloguedb:
    image: :mongo

  basketdb:
    image: :redis:alpine

  discountdb:
    image: :postgres
   
  portainer:
    image: :portainer/portainer-ce

  catalogueapi:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue.API/CatalogueAPI/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  

